/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsCollectionIndexRouteImport } from './routes/collections/$collection/index'
import { Route as CollectionsCollectionCreateRouteImport } from './routes/collections/$collection/create'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collection/$id/index'
import { Route as CollectionsCollectionIdApiRouteImport } from './routes/collections/$collection/$id/api'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIndexRoute =
  CollectionsCollectionIndexRouteImport.update({
    id: '/collections/$collection/',
    path: '/collections/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionCreateRoute =
  CollectionsCollectionCreateRouteImport.update({
    id: '/collections/$collection/create',
    path: '/collections/$collection/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collection/$id/',
    path: '/collections/$collection/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionIdApiRoute =
  CollectionsCollectionIdApiRouteImport.update({
    id: '/collections/$collection/$id/api',
    path: '/collections/$collection/$id/api',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$collection/create': typeof CollectionsCollectionCreateRoute
  '/collections/$collection': typeof CollectionsCollectionIndexRoute
  '/collections/$collection/$id/api': typeof CollectionsCollectionIdApiRoute
  '/collections/$collection/$id': typeof CollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/$collection/create': typeof CollectionsCollectionCreateRoute
  '/collections/$collection': typeof CollectionsCollectionIndexRoute
  '/collections/$collection/$id/api': typeof CollectionsCollectionIdApiRoute
  '/collections/$collection/$id': typeof CollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/$collection/create': typeof CollectionsCollectionCreateRoute
  '/collections/$collection/': typeof CollectionsCollectionIndexRoute
  '/collections/$collection/$id/api': typeof CollectionsCollectionIdApiRoute
  '/collections/$collection/$id/': typeof CollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/$collection/create'
    | '/collections/$collection'
    | '/collections/$collection/$id/api'
    | '/collections/$collection/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/$collection/create'
    | '/collections/$collection'
    | '/collections/$collection/$id/api'
    | '/collections/$collection/$id'
  id:
    | '__root__'
    | '/'
    | '/collections/$collection/create'
    | '/collections/$collection/'
    | '/collections/$collection/$id/api'
    | '/collections/$collection/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsCollectionCreateRoute: typeof CollectionsCollectionCreateRoute
  CollectionsCollectionIndexRoute: typeof CollectionsCollectionIndexRoute
  CollectionsCollectionIdApiRoute: typeof CollectionsCollectionIdApiRoute
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/': {
      id: '/collections/$collection/'
      path: '/collections/$collection'
      fullPath: '/collections/$collection'
      preLoaderRoute: typeof CollectionsCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/create': {
      id: '/collections/$collection/create'
      path: '/collections/$collection/create'
      fullPath: '/collections/$collection/create'
      preLoaderRoute: typeof CollectionsCollectionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/$id/': {
      id: '/collections/$collection/$id/'
      path: '/collections/$collection/$id'
      fullPath: '/collections/$collection/$id'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/$id/api': {
      id: '/collections/$collection/$id/api'
      path: '/collections/$collection/$id/api'
      fullPath: '/collections/$collection/$id/api'
      preLoaderRoute: typeof CollectionsCollectionIdApiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsCollectionCreateRoute: CollectionsCollectionCreateRoute,
  CollectionsCollectionIndexRoute: CollectionsCollectionIndexRoute,
  CollectionsCollectionIdApiRoute: CollectionsCollectionIdApiRoute,
  CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
